# Force Nixpacks usage for Railway deployment

providers = ["node"]

[variables]
NODE_ENV = "production"

[phases.install]
cmd = "npm ci --prefer-offline --no-audit"

[phases.build]
cmd = "npm run build"

[start]
cmd = "npm start"
